name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build & Publish PHP 8.1 Buster
      run: sh build.sh php81-buster -p
      
    - name: Build & Publish PHP 8.1 Buster Puppeteer
      run: sh build.sh php81-buster-puppeteer -p

    - name: Build & Publish PHP 8.1 Buster Libre Office
      run: sh build.sh php81-buster-puppeteer -p
